// AUTO-GENERATED by scripts/sync-projects.mjs — do not edit manually
import p0 from "../../../content/projects/agent-preset-desktop.json";
import p1 from "../../../content/projects/cloud-knowledge-base.json";
import p2 from "../../../content/projects/file-manager.json";

import type { ProjectSource } from "./projects.types";

export const projectSources: ProjectSource[] = [p0, p1, p2];
